apiVersion: v2
name: renomy-app-template-secret
description: renomy-app-template-secret
type: application
icon: 'https://github.com/projectkerberus/kerberus-dashboard/blob/main/docs/media/square_black_logo.png'

version: 0.1.2
appVersion: 0.1.2

maintainers:
  - name: Mauro Sala
    email: mauro.sala@kiratech.it
    url: https://www.kiratech.it
