apiVersion: v1
data:
  endpoint: {{ .Values.endpoint | b64enc }}
  password: {{ .Values.password | b64enc }}
  publicIP: {{ .Values.publicIP | b64enc }}
  username: {{ .Values.username | b64enc }}
kind: Secret
metadata:
  name: cloudsqlpostgresql-conn
  namespace: {{ .Release.Namespace }}
type: Secret
