{{- if .Values.endpoint }}
---
{{- end }}
apiVersion: v1
data:
  endpoint: {{ .Values.endpoint | b64enc }}
  password: {{ .Values.password | b64enc }}
  port: {{ .Values.port | b64enc }}
  username: {{ .Values.username | b64enc }}
kind: Secret
metadata:
  name: rdsmariadbql-conn
  namespace: {{ .Release.Namespace }}
type: connection.crossplane.io/v1alpha1
